POST http://localhost:3001/api/blogs/
Content-Type: application/json

{
    "url": "https://fullstackopen.com/osa4/token_perustainen_kirjautuminen",
    "title": "Full stack part 4",
    "author": "joel",
    "likes": 3,
    "userId": "6349616d53739e374c31b6e0"
}